//@version=4
//目前我最好的策略
strategy("Supertrend Strategy", overlay=true, initial_capital=100000, default_qty_type=strategy.percent_of_equity, default_qty_value=100)

// Strategy Parameters
Periods = input(title="ATR Period", type=input.integer, defval=10)
src = input(hl2, title="Source")
Multiplier = input(title="ATR Multiplier", type=input.float, step=0.1, defval=3.0)
changeATR = input(title="Change ATR Calculation Method ?", type=input.bool, defval=true)
showsignals = input(title="Show Buy/Sell Signals ?", type=input.bool, defval=true)
highlighting = input(title="Highlighter On/Off ?", type=input.bool, defval=true)

// Additional Strategy Parameters
useStopLoss = input(title="Use Stop Loss?", type=input.bool, defval=true)
stopLossPercent = input(title="Stop Loss %", type=input.float, defval=2.0, minval=0.1, step=0.1)
useTakeProfit = input(title="Use Take Profit?", type=input.bool, defval=true)
takeProfitPercent = input(title="Take Profit %", type=input.float, defval=4.0, minval=0.1, step=0.1)

// Calculate Supertrend
atr2 = sma(tr, Periods)
atr = changeATR ? atr(Periods) : atr2
up = src-(Multiplier*atr)
up1 = nz(up[1],up)
up := close[1] > up1 ? max(up,up1) : up
dn = src+(Multiplier*atr)
dn1 = nz(dn[1], dn)
dn := close[1] < dn1 ? min(dn, dn1) : dn
trend = 1
trend := nz(trend[1], trend)
trend := trend == -1 and close > dn1 ? 1 : trend == 1 and close < up1 ? -1 : trend

// Plot Supertrend
upPlot = plot(trend == 1 ? up : na, title="Up Trend", style=plot.style_linebr, linewidth=2, color=color.green)
dnPlot = plot(trend == 1 ? na : dn, title="Down Trend", style=plot.style_linebr, linewidth=2, color=color.red)
mPlot = plot(ohlc4, title="", style=plot.style_circles, linewidth=0)

// Highlighting
longFillColor = highlighting ? (trend == 1 ? color.green : color.white) : color.white
shortFillColor = highlighting ? (trend == -1 ? color.red : color.white) : color.white
fill(mPlot, upPlot, title="UpTrend Highligter", color=longFillColor)
fill(mPlot, dnPlot, title="DownTrend Highligter", color=shortFillColor)

// Trading Signals
buySignal = trend == 1 and trend[1] == -1
sellSignal = trend == -1 and trend[1] == 1

// Plot Signals
plotshape(buySignal and showsignals ? up : na, title="Buy", text="Buy", location=location.absolute, style=shape.labelup, size=size.tiny, color=color.green, textcolor=color.white, transp=0)
plotshape(sellSignal and showsignals ? dn : na, title="Sell", text="Sell", location=location.absolute, style=shape.labeldown, size=size.tiny, color=color.red, textcolor=color.white, transp=0)

// Strategy Execution
if (buySignal)
    strategy.entry("Long", strategy.long)
    if useStopLoss
        strategy.exit("SL/TP", "Long", stop=strategy.position_avg_price * (1 - stopLossPercent/100), limit=strategy.position_avg_price * (1 + takeProfitPercent/100))

if (sellSignal)
    strategy.close("Long")

// Plot strategy equity
plot(strategy.equity, title="Equity", color=color.blue, style=plot.style_stepline)
